### ISSUE TITLE
Is there any api documents?

### ISSUE THREAD

**Issue by jy1989** [WhitestormJS/react-whs#1]
Hi

Thanks for your awesome library,

But without the documents. I don't know how to set the parameter to the components.

Thank you very much.

**Comment by sasha240100** [comment]
@jy1989 react-whs is yet in development, but you can already use it). All your react props are passed to component as parameters. What do you want to make?

**Comment by sasha240100** [comment]
@jy1989 See https://github.com/WhitestormJS/react-whs#propertiesparams-syntax
