### ISSUE TITLE
Cannot resolve module 'WHS'

### ISSUE THREAD

**Issue by pfulop** [WhitestormJS/react-whs#3]
Importing module  in react project throws error:
ERROR in ./\~/react-whs/build/react-whs.js
Module not found: Error: Cannot resolve module 'WHS' in /home/user/threejs/node_modules/react-whs/build
 @ ./~/react-whs/build/react-whs.js 1:82-96

Is there any special webpack configuration needed?

**Comment by sasha240100** [comment]
@pfulop. That happens even with latest bundle? The error comes from webpack config where I forgot to set the package name for `commonjs2` type. Can you please try doing `npm install` with latest version? If error still exists - then I'll do a build and publish a new version to npm

**Comment by pfulop** [comment]
Yeah I tried reinstalling didn't help. However changing package.json to include your module from git directly  helped.
``    "react-whs": "https://github.com/WhitestormJS/react-whs.git",``

So npm has just bad version? Maybe?

**Comment by sasha240100** [comment]
@pfulop The error is because of this: https://github.com/WhitestormJS/react-whs/blob/master/webpack.config.babel.js#L27

**Comment by pfulop** [comment]
you are suggesting sticking to including it directly from repository?

**Comment by sasha240100** [comment]
@pfulop I'll make a build and publish a new version now.

**Comment by pfulop** [comment]
Thank you very much.

**Comment by sasha240100** [comment]
@pfulop Done. Check now. v1.1.4

**Comment by sasha240100** [comment]
@pfulop Works? Can you test it?

**Comment by pfulop** [comment]
It works now, thanks ;)

Also, maybe it would be good to add whs as a dependency? Same as three is dependency for whs:
https://github.com/WhitestormJS/whitestorm.js/blob/beta/package.json#L33

**Comment by sasha240100** [comment]
@pfulop Makes sense. Thanks. Will do v1.1.5 now =)

**Comment by pfulop** [comment]
By the way, really great work.

I guess I can close this now.

**Comment by sasha240100** [comment]
@pfulop Done, thanks!
