### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/react-whs#4]
Some of dependencies should be updated in `package.json`. **Current situation**:

![image](https://cloud.githubusercontent.com/assets/7657429/23141777/1c65517c-f7c1-11e6-8452-e61d5c7ad35a.png)

- [ ] babel, babel-cli, babel-loader
- [ ] All babel plugins
- [ ] webpack-dev-server

**Comment by panamantis** [comment]
Yeah, I can't find a combination of dependencies that gets me past the decorator syntax @

> Module parse failed: C:\scripts-17\whitestorm\-- sources\react-whs-master\node_modules\whs\src\core\MeshComponent.js Unexpected character '@' (7:0)

**Comment by sasha240100** [comment]
@panamantis Should be. https://github.com/WhitestormJS/react-whs/blob/32c767e1fef3e05da11aaf81c17ddedd3802a49d/package.json#L21

**Comment by sasha240100** [comment]
@panamantis Ah, okay, now I see. There is no plugin in `.babelrc`

**Comment by hirako2000** [comment]
I m looking into it. will also update some libs to latest

**Comment by sasha240100** [comment]
@hirako2000 I'm doing it now

**Comment by panamantis** [comment]
(I won't reopen this) But I'm having the same "Unexpected character"/"Unexpected token".  Think it's related to the legacy plugin.  npm version 4.5, rebuilt things.  Maybe my "npm start" command isn't picking up the babel config?
Thanks for jumping on upgrading the packages above.

**Comment by sasha240100** [comment]
@panamantis I found some problems with `react-whs`. Trying to solve them now. Will update once I solve
