### ISSUE TITLE
Add refComponent to App component

### ISSUE THREAD

**Issue by tpflueger** [WhitestormJS/react-whs#5]
Need ability to access refComponent of the App to use Loop and other controls.

**Comment by sasha240100** [comment]
Issue related to #2. Going to implement

**Comment by sasha240100** [comment]
@tpflueger implemented as `refApp` in https://github.com/WhitestormJS/react-whs/commit/0b1183cadee1b32ffe2758555b4fb068cb3db634. Now available in `v1.1.6`
