### ISSUE TITLE
Missing required loader

### ISSUE THREAD

**Issue by jarrodmedrano** [WhitestormJS/react-whs#7]
ERROR in ./~/whs/src/components/cameras/OrthographicCamera.js
Module parse failed: C:\src\react-whs\node_modules\whs\src\components\cameras\OrthographicCamera.js Unexpected token (6:18)
You may need an appropriate loader to handle this file type.

**Comment by tacomoney** [comment]
I fixed this by removing  exclude: /node_modules/, from the webpack configs.

**Comment by sasha240100** [comment]
@tacomoney Seems like it uses sources (uncompiled)

**Comment by jarrodmedrano** [comment]
This still doesn't work from a clean install.

**Comment by hirako2000** [comment]
How are you setup, is there a repo somewhere? Suspect some config is incorrect

**Comment by jarrodmedrano** [comment]
Yes I have a repo here (this works for me)
https://github.com/jarrodmedrano/react-whitestorm-js

I had to remove the exclude node_modules lines as well as install some babel plugins and lock the version numbers of npm packages. I'm not sure exactly where the snafu comes from but I had the same problem on mac and windows.

**Comment by hirako2000** [comment]
strange it works for me.
```
npm install
npm start
```

![image](https://user-images.githubusercontent.com/1500712/28276394-ff2136b4-6b40-11e7-8073-346dfd13bbba.png)

**Comment by jarrodmedrano** [comment]
Yes it works after I changed all of those things. It doesn't work when I clone and install and start it from your repo.

**Comment by hirako2000** [comment]
Ah ok got it !

What we will do is upgrade a bunch of things. `whs` now uses rollup, which makes it much more lightweight. I spotted a few other issues with modules missing some deps. users should not have to install them manually.

thanks for pointing out the issues you faced.

**Comment by jarrodmedrano** [comment]
No problem. Cool, looking forward to the upgrades.
